export interface SearchEntry {
  title: string;
  href: string;
  section: string;
  description: string;
  keywords: string;
}

export const SEARCH_INDEX: SearchEntry[] = [
  // Introduction
  {
    title: 'Documentation overview',
    href: '/docs',
    section: 'Introduction',
    description: 'What Sagewai is and where to start.',
    keywords: 'overview introduction docs start here sagewai sdk platform',
  },

  // Get Started
  {
    title: 'Installation',
    href: '/docs/get-started/installation',
    section: 'Get Started',
    description: 'Install the Sagewai SDK with pip or uv, install optional extras, and verify the install.',
    keywords: 'installation install pip uv sagewai sdk fastapi postgres extras python',
  },
  {
    title: 'Prerequisites',
    href: '/docs/get-started/prerequisites',
    section: 'Get Started',
    description: 'Python 3.10+, Docker, hardware profiles, and cloud instance sizing.',
    keywords: 'prerequisites python docker hardware ram cpu gpu disk requirements',
  },
  {
    title: 'Your first agent',
    href: '/docs/get-started/first-agent',
    section: 'Get Started',
    description: 'Five lines of Python. Your first Sagewai agent running against any LLM.',
    keywords: 'first agent hello world quickstart build run UniversalAgent install pip',
  },
  {
    title: 'Full quickstart',
    href: '/docs/get-started/quickstart',
    section: 'Get Started',
    description: 'End-to-end setup with sandbox, tools, and the admin panel.',
    keywords: 'getting started setup sandbox claude code admin panel full quickstart',
  },
  {
    title: 'Minimal setup — no sandbox',
    href: '/docs/get-started/minimal-setup',
    section: 'Get Started',
    description: 'SDK only: no Docker, no admin server. Fastest path to a working agent.',
    keywords: 'minimal setup no docker no sandbox lightweight install sdk only',
  },

  // Core Concepts
  {
    title: 'Agents',
    href: '/docs/core-concepts/agents',
    section: 'Core Concepts',
    description: 'BaseAgent, UniversalAgent, GoogleNativeAgent — the agent hierarchy.',
    keywords: 'agents baseagent universalagent googlenativeagent hierarchy events tools',
  },
  {
    title: 'Strategies',
    href: '/docs/core-concepts/strategies',
    section: 'Core Concepts',
    description: 'ReAct, Chain-of-Thought, and custom execution strategies.',
    keywords: 'strategies react chain of thought execution cot planning',
  },
  {
    title: 'Memory & RAG',
    href: '/docs/core-concepts/memory',
    section: 'Core Concepts',
    description: 'Vector memory, episodic memory, RAG retrieval, and extraction strategies.',
    keywords: 'memory rag vector episodic retrieval extraction milvus recall',
  },
  {
    title: 'Workflows',
    href: '/docs/core-concepts/workflows',
    section: 'Core Concepts',
    description: 'YAML-defined multi-step workflows with branching and parallel execution.',
    keywords: 'workflows yaml multi-step branching parallel sequential dag',
  },
  {
    title: 'Context Engine',
    href: '/docs/core-concepts/context-engine',
    section: 'Core Concepts',
    description: 'Automatic context compaction, episode management, and sliding windows.',
    keywords: 'context engine compaction episode management sliding window tokens',
  },
  {
    title: 'Directives',
    href: '/docs/core-concepts/directives',
    section: 'Core Concepts',
    description: 'Structured behavioural constraints injected into every agent call.',
    keywords: 'directives behavioural constraints inject structured rules persona',
  },
  {
    title: 'Safety & Guardrails',
    href: '/docs/core-concepts/safety',
    section: 'Core Concepts',
    description: 'Input/output guardrails for PII, hallucination, and content safety.',
    keywords: 'safety guardrails pii hallucination content moderation input output',
  },
  {
    title: 'Self-Learning Agents',
    href: '/docs/core-concepts/self-learning',
    section: 'Core Concepts',
    description: 'Curator, preference learning, and training data collection from production.',
    keywords: 'self-learning curator preference training data collection production',
  },

  // Platform
  {
    title: 'Platform overview',
    href: '/docs/platform',
    section: 'Platform',
    description: 'The Sagewai platform components: SDK, Autopilot, Fleet, Observatory, Training Loop, Sealed.',
    keywords: 'platform overview sdk autopilot fleet observatory training loop sealed security',
  },
  {
    title: 'SDK',
    href: '/docs/platform/sdk',
    section: 'Platform',
    description: 'Python-native agent runtime with 100+ LLM providers, MCP tools, and typed memory.',
    keywords: 'sdk python agent runtime llm providers mcp tools memory guardrails',
  },
  {
    title: 'Autopilot',
    href: '/docs/platform/autopilot',
    section: 'Platform',
    description: 'Goal-driven agent orchestration — state the goal, Autopilot runs the mission.',
    keywords: 'autopilot goal mission orchestration blueprint slotspec agentgraph',
  },
  {
    title: 'Fleet',
    href: '/docs/platform/fleet',
    section: 'Platform',
    description: 'Distributed workers with capability dispatch, enrollment keys, and sandbox isolation.',
    keywords: 'fleet workers distributed dispatch enrollment keys sandbox capability',
  },
  {
    title: 'Observatory',
    href: '/docs/platform/observatory',
    section: 'Platform',
    description: 'OpenTelemetry tracing, metrics, Grafana dashboards, and cost audit trail.',
    keywords: 'observatory otel tracing metrics grafana dashboards cost audit',
  },
  {
    title: 'Training Loop',
    href: '/docs/platform/training-loop',
    section: 'Platform',
    description: 'Curate runs, export datasets, fine-tune a model, deploy it. Agents that get cheaper with use.',
    keywords: 'training loop fine-tune unsloth export alpaca curate cheaper cost',
  },
  {
    title: 'Security — Sealed',
    href: '/docs/platform/security',
    section: 'Platform',
    description: 'Sealed: the cross-cutting security layer — profiles, JIT-HITL, tool scopes, sandbox tiers.',
    keywords: 'sealed security profiles jit hitl tool scopes sandbox tiers tier-1 tier-2',
  },

  // Guides
  {
    title: 'Multi-Agent Workflows',
    href: '/docs/guides/multi-agent',
    section: 'Guides',
    description: 'Orchestrate multiple agents with delegation, pipelines, and parallel execution.',
    keywords: 'multi-agent workflows orchestrate delegation pipeline parallel',
  },
  {
    title: 'Training & Fine-Tuning',
    href: '/docs/guides/training',
    section: 'Guides',
    description: 'Collect training data, fine-tune a model, deploy it, run $0/token.',
    keywords: 'training fine-tuning unsloth collect data export alpaca slm model',
  },
  {
    title: 'Admin Panel',
    href: '/docs/guides/admin-panel',
    section: 'Guides',
    description: 'Set up and use the Sagewai admin panel: orgs, projects, agents, observability.',
    keywords: 'admin panel setup org project agents observability config ui dashboard',
  },
  {
    title: 'Fleet Deployment',
    href: '/docs/guides/fleet-deployment',
    section: 'Guides',
    description: 'Deploy and manage fleet workers at scale.',
    keywords: 'fleet deployment workers scale dispatch capabilities labels',
  },
  {
    title: 'Fleet Architecture',
    href: '/docs/guides/fleet-architecture',
    section: 'Guides',
    description: 'In-depth technical guide to the fleet dispatch and isolation model.',
    keywords: 'fleet architecture dispatch isolation model technical workers mtls anomaly',
  },
  {
    title: 'Self-Hosted Deployment',
    href: '/docs/guides/self-hosted',
    section: 'Guides',
    description: 'Run Sagewai on your own infrastructure with Docker and docker-compose.',
    keywords: 'self-hosted deployment docker compose on-premise infrastructure production',
  },
  {
    title: 'Infrastructure Management',
    href: '/docs/guides/infrastructure',
    section: 'Guides',
    description: 'Manage LLM providers, proxy endpoints, and API keys via the admin panel.',
    keywords: 'infrastructure management providers api keys proxy admin config',
  },
  {
    title: 'MCP Server',
    href: '/docs/guides/mcp-server',
    section: 'Guides',
    description: 'Expose tools via the Model Context Protocol (MCP) gateway.',
    keywords: 'mcp server model context protocol gateway tools expose',
  },
  {
    title: 'External Access',
    href: '/docs/guides/external-access',
    section: 'Guides',
    description: 'Expose the admin API and MCP gateway to external clients.',
    keywords: 'external access api gateway expose ngrok cloudflare tunnel',
  },
  {
    title: 'Gateway Streaming',
    href: '/docs/guides/gateway-streaming',
    section: 'Guides',
    description: 'Server-sent events (SSE) streaming through the gateway.',
    keywords: 'gateway streaming sse server-sent events real-time stream',
  },
  {
    title: 'LLM Harness',
    href: '/docs/guides/harness',
    section: 'Guides',
    description: 'Smart proxy that routes LLM calls to the cheapest capable model per request.',
    keywords: 'harness proxy llm routing cheapest model cost save haiku sonnet opus',
  },
  {
    title: 'Cost Management',
    href: '/docs/guides/cost-management',
    section: 'Guides',
    description: 'Per-project budgets, spend tracking, rate limits, and cost alerts.',
    keywords: 'cost management budget spend tracking rate limit alert billing',
  },
  {
    title: 'PII Protection',
    href: '/docs/guides/pii-protection',
    section: 'Guides',
    description: 'Detect and redact PII before it reaches the LLM.',
    keywords: 'pii protection detect redact personal data privacy guardrail',
  },
  {
    title: 'Local Inference',
    href: '/docs/guides/local-inference',
    section: 'Guides',
    description: 'Ollama, vLLM, LM Studio, and llama.cpp — zero API cost, data stays local.',
    keywords: 'local inference ollama vllm lm studio llama.cpp zero cost data local',
  },
  {
    title: 'Small and Local Models',
    href: '/docs/guides/small-models',
    section: 'Guides',
    description: 'Choosing and running small language models for cost-sensitive workloads.',
    keywords: 'small models local slm quantized cost-sensitive workloads gguf',
  },
  {
    title: 'CI/CD Integration',
    href: '/docs/guides/ci-cd',
    section: 'Guides',
    description: 'Integrate Sagewai agents into your CI/CD pipeline.',
    keywords: 'ci cd pipeline integration github actions devops deploy automation',
  },
  {
    title: 'VS Code Extension',
    href: '/docs/guides/vscode-extension',
    section: 'Guides',
    description: 'Use the Sagewai extension to manage agents from within VS Code.',
    keywords: 'vscode extension visual studio code ide editor plugin',
  },
  {
    title: 'Client Wrappers (17 Languages)',
    href: '/docs/guides/client-wrappers',
    section: 'Guides',
    description: 'Official thin client wrappers: TypeScript, Go, Rust, Java, and 13 more.',
    keywords: 'client wrappers typescript go rust java python languages sdk wrapper',
  },
  {
    title: 'Integrations',
    href: '/docs/guides/integrations',
    section: 'Guides',
    description: 'Connect Sagewai to external systems, APIs, and tools.',
    keywords: 'integrations external systems api tools connectors mcp',
  },
  {
    title: 'Video Tutorials',
    href: '/docs/guides/video-tutorials',
    section: 'Guides',
    description: 'Video walkthroughs for common Sagewai patterns and use cases.',
    keywords: 'video tutorials walkthrough patterns use cases examples',
  },
  {
    title: 'vs. Alternatives',
    href: '/docs/guides/vs-alternatives',
    section: 'Guides',
    description: 'Sagewai compared to LangChain, LlamaIndex, CrewAI, AutoGen, and Semantic Kernel.',
    keywords: 'comparison alternatives langchain llamaindex crewai autogen semantic kernel',
  },
  {
    title: 'vs. MiniMax',
    href: '/docs/guides/vs-minimax',
    section: 'Guides',
    description: 'Sagewai vs MiniMax: model support, fleet, memory, and training loop.',
    keywords: 'minimax comparison model support fleet memory training loop',
  },

  // Inference
  {
    title: 'Inference overview',
    href: '/docs/inference',
    section: 'Inference',
    description: 'Choosing and deploying inference backends: cloud APIs, GPU cloud, local.',
    keywords: 'inference overview cloud api gpu local ollama vllm runpod modal colab',
  },
  {
    title: 'Start with the big providers',
    href: '/docs/inference/start-with-juggernauts',
    section: 'Inference',
    description: 'OpenAI, Anthropic, Google — use the big providers while prototyping.',
    keywords: 'openai anthropic google gpt claude gemini cloud api inference providers',
  },
  {
    title: 'Free CUDA via Colab',
    href: '/docs/inference/free-cuda-via-colab',
    section: 'Inference',
    description: 'Run GPU inference for free with Google Colab.',
    keywords: 'free cuda colab google gpu inference vllm cheap cost',
  },
  {
    title: 'Rent when you grow',
    href: '/docs/inference/rent-when-you-grow',
    section: 'Inference',
    description: 'RunPod, Modal, and Vast.ai for scalable GPU inference.',
    keywords: 'runpod modal vast ai gpu rent scale inference serverless',
  },
  {
    title: 'Deploy locally',
    href: '/docs/inference/deploy-locally',
    section: 'Inference',
    description: 'Ollama, vLLM, LM Studio, and llama.cpp on your own hardware.',
    keywords: 'local deploy ollama vllm lm studio llama.cpp on-premise hardware',
  },

  // Tutorials
  {
    title: 'Tutorials overview',
    href: '/docs/tutorials',
    section: 'Tutorials',
    description: 'End-to-end walkthroughs that build complete systems step by step.',
    keywords: 'tutorials overview end-to-end walkthroughs step by step',
  },
  {
    title: 'Learn the SDK step by step',
    href: '/docs/tutorials/learn-the-sdk',
    section: 'Tutorials',
    description: 'SDK basics: agents, tools, memory, strategies, and workflows.',
    keywords: 'learn sdk basics agents tools memory strategies workflows step by step',
  },
  {
    title: 'Train your own model',
    href: '/docs/tutorials/train-your-own-model',
    section: 'Tutorials',
    description: 'Curate runs, fine-tune with Unsloth, deploy with Ollama. Zero cost per token at the limit.',
    keywords: 'train fine-tune unsloth ollama gguf training loop slm custom model',
  },
  {
    title: 'Moderation and classification',
    href: '/docs/tutorials/moderation-and-classification',
    section: 'Tutorials',
    description: 'Content moderation, PII detection, and multi-label classification with tool-calling agents.',
    keywords: 'moderation classification pii content safety guardrails label',
  },
  {
    title: 'Memory and retrieval',
    href: '/docs/tutorials/memory-and-retrieval',
    section: 'Tutorials',
    description: 'RAG, vector memory, episodic memory, and extraction strategies.',
    keywords: 'memory rag retrieval vector milvus episodic extraction strategies',
  },
  {
    title: 'Production multitenancy',
    href: '/docs/tutorials/production-multitenancy',
    section: 'Tutorials',
    description: 'Project isolation, fleet workers, enrollment keys, and cross-project governance.',
    keywords: 'multitenancy projects isolation fleet workers enrollment keys governance',
  },
  {
    title: 'Observability and cost',
    href: '/docs/tutorials/observability-and-cost',
    section: 'Tutorials',
    description: 'OpenTelemetry, Grafana dashboards, per-project cost tracking, and audit logs.',
    keywords: 'observability cost otel grafana prometheus metrics tracing audit logs',
  },
  {
    title: 'Inference deployment',
    href: '/docs/tutorials/inference-deployment',
    section: 'Tutorials',
    description: 'Deploy fine-tuned models to Ollama, vLLM, RunPod, Modal, and Vast.ai.',
    keywords: 'inference deployment ollama vllm runpod modal vast gpu cloud local',
  },
  {
    title: 'Production patterns',
    href: '/docs/tutorials/production-patterns',
    section: 'Tutorials',
    description: 'Production reference patterns for real-world agent deployments.',
    keywords: 'patterns production reference real world deployment best practices',
  },

  // Architecture
  {
    title: 'Architecture overview',
    href: '/docs/architecture',
    section: 'Architecture',
    description: 'Canonical runtime architecture: topology, security tiers, execution modes, backends.',
    keywords: 'architecture overview runtime topology security tiers execution modes backends',
  },
  {
    title: 'Runtime Topology',
    href: '/docs/architecture/runtime-topology',
    section: 'Architecture',
    description: 'How SDK, gateway, fleet, and admin interconnect at runtime.',
    keywords: 'runtime topology sdk gateway fleet admin interconnect diagram',
  },
  {
    title: 'Security Tiers',
    href: '/docs/architecture/security-tiers',
    section: 'Architecture',
    description: 'TRUSTED, SANDBOXED, UNTRUSTED tier model and what runs in each.',
    keywords: 'security tiers trusted sandboxed untrusted tier model',
  },
  {
    title: 'Execution Modes',
    href: '/docs/architecture/execution-modes',
    section: 'Architecture',
    description: 'Direct, fleet, autopilot, and harness execution modes explained.',
    keywords: 'execution modes direct fleet autopilot harness proxy',
  },
  {
    title: 'Sandbox Backends',
    href: '/docs/architecture/sandbox-backends',
    section: 'Architecture',
    description: 'Docker, Kubernetes, and AgentCore sandbox backend implementations.',
    keywords: 'sandbox backends docker kubernetes agentcore k8s container isolation',
  },

  // Reference
  {
    title: 'Examples (numbered file list)',
    href: '/docs/reference/examples',
    section: 'Reference',
    description: 'All 50+ runnable example scripts, numbered by topic.',
    keywords: 'examples numbered list runnable scripts demos',
  },
  {
    title: 'API — Python SDK',
    href: '/docs/api-reference/python-sdk',
    section: 'Reference',
    description: 'Top-level Python SDK API surface.',
    keywords: 'api python sdk reference import surface',
  },
  {
    title: 'API — Agents',
    href: '/docs/api-reference/agents',
    section: 'Reference',
    description: 'BaseAgent, UniversalAgent, GoogleNativeAgent API reference.',
    keywords: 'api reference agents baseagent universalagent googlenativeagent parameters',
  },
  {
    title: 'API — Strategies',
    href: '/docs/api-reference/strategies',
    section: 'Reference',
    description: 'Execution strategy API: ReAct, COT, and custom strategies.',
    keywords: 'api strategies react cot chain of thought execution reference',
  },
  {
    title: 'API — Memory & Context',
    href: '/docs/api-reference/memory',
    section: 'Reference',
    description: 'ContextEngine, RAGEngine, MemoryBranch, and strategy classes.',
    keywords: 'api memory context engine rag engine branch strategy classes',
  },
  {
    title: 'API — Workflows',
    href: '/docs/api-reference/workflows',
    section: 'Reference',
    description: 'YAML workflow builder, executor, and step types.',
    keywords: 'api workflows yaml builder executor step types',
  },
  {
    title: 'API — Safety & Guardrails',
    href: '/docs/api-reference/safety',
    section: 'Reference',
    description: 'Guardrail classes for PII, hallucination, and content safety.',
    keywords: 'api safety guardrails pii hallucination content',
  },
  {
    title: 'API — Directives',
    href: '/docs/api-reference/directives',
    section: 'Reference',
    description: 'DirectiveEngine and built-in directive types.',
    keywords: 'api directives engine types behavioural constraints',
  },
  {
    title: 'API — Self-Learning',
    href: '/docs/api-reference/self-learning',
    section: 'Reference',
    description: 'Curator, TrainingDataset, and preference learning classes.',
    keywords: 'api self-learning curator training dataset preference',
  },
  {
    title: 'API — Project & Errors',
    href: '/docs/api-reference/project',
    section: 'Reference',
    description: 'Project configuration, error types, and exception hierarchy.',
    keywords: 'api project errors exceptions configuration hierarchy',
  },
  {
    title: 'API — Tools & MCP',
    href: '/docs/api-reference/tools',
    section: 'Reference',
    description: 'ToolSpec, @tool decorator, and MCP tool integration.',
    keywords: 'api tools mcp toolspec decorator integration gateway',
  },
  {
    title: 'API — MCP Protocol',
    href: '/docs/api-reference/mcp',
    section: 'Reference',
    description: 'Model Context Protocol server and client API.',
    keywords: 'api mcp model context protocol server client',
  },
  {
    title: 'API — Notifications',
    href: '/docs/api-reference/notifications',
    section: 'Reference',
    description: 'Email and webhook notification API.',
    keywords: 'api notifications email webhook resend sendgrid postmark',
  },
  {
    title: 'API — REST',
    href: '/docs/api-reference/rest-api',
    section: 'Reference',
    description: 'Full REST API reference for the admin panel backend.',
    keywords: 'api rest reference admin backend endpoints http',
  },

  // Blog
  {
    title: 'Introducing Sagewai',
    href: '/docs/blog/introducing-sagewai',
    section: 'Blog',
    description: 'The announcement and vision behind the Sagewai platform.',
    keywords: 'blog introducing sagewai announcement vision launch',
  },
];
