/**
 * Auth token management — access token in memory only; httpOnly cookies
 * are issued server-side by the login API.
 *
 * Security model:
 *  - Access token: stored in module-level variable (in-memory). Never written
 *    to localStorage or a JS-accessible cookie, so it cannot be stolen via XSS.
 *  - Refresh token: stored in an httpOnly Secure SameSite=Strict cookie set by
 *    the server on login/refresh. Not accessible from JavaScript at all.
 *  - sagewai_auth cookie: set httpOnly by the server; used by Next.js middleware
 *    to gate routes without exposing any token value.
 *
 * On page reload the in-memory access token is gone. Call silentRefresh() on
 * app mount to obtain a fresh access token from the server (which reads the
 * httpOnly refresh cookie automatically).
 *
 * Local development:
 *  - Run `make dev-setup` to generate a dev JWT and write it to .env.local.
 *  - The NEXT_PUBLIC_ADMIN_DEV_TOKEN env var provides a valid JWT that the
 *    backend accepts through its normal auth middleware — no security bypass.
 */

const BASE_URL =
  process.env.NEXT_PUBLIC_ADMIN_API_URL?.replace(/\/admin$/, '') ?? '';

/**
 * Dev token — a valid JWT generated by `make dev-setup` using the same
 * ADMIN_JWT_SECRET. Used as fallback when no in-memory access token exists
 * and silentRefresh() hasn't been called yet. Only available in local dev.
 */
const DEV_TOKEN = process.env.NEXT_PUBLIC_ADMIN_DEV_TOKEN ?? '';

/** In-memory access token — never persisted to localStorage or cookies. */
let _accessToken: string | null = null;

export function getAccessToken(): string | null {
  return _accessToken || DEV_TOKEN || null;
}

/**
 * Store the access token in memory only.
 * The refresh token and auth indicator cookie are set server-side (httpOnly)
 * by the login/refresh API response — the browser stores them automatically.
 */
export function setTokens(accessToken: string): void {
  _accessToken = accessToken;
}

/**
 * Clear the in-memory access token and call the logout endpoint so the
 * server clears the httpOnly cookies.
 */
export function clearTokens(): void {
  _accessToken = null;
  if (typeof window !== 'undefined' && BASE_URL) {
    fetch(`${BASE_URL}/api/v1/auth/logout`, {
      method: 'POST',
      credentials: 'include',
    }).catch(() => {});
  }
}

/**
 * Attempt a silent token refresh using the httpOnly refresh cookie.
 * Returns the new access token on success, or null on failure (user must log in).
 *
 * Falls back to DEV_TOKEN for local development (generated by `make dev-setup`).
 */
export async function silentRefresh(): Promise<string | null> {
  if (!BASE_URL) {
    // No API URL configured — use dev token if available
    if (DEV_TOKEN) {
      _accessToken = DEV_TOKEN;
      return _accessToken;
    }
    return null;
  }
  try {
    const resp = await fetch(`${BASE_URL}/api/v1/auth/refresh`, {
      method: 'POST',
      credentials: 'include',
    });
    if (resp.ok) {
      const data = await resp.json();
      if (data.access_token) {
        _accessToken = data.access_token;
        return _accessToken;
      }
    }
  } catch {
    // Network error — fall through
  }
  // Refresh failed — use dev token if available (local dev only)
  if (DEV_TOKEN) {
    _accessToken = DEV_TOKEN;
    return _accessToken;
  }
  return null;
}

export function isAuthenticated(): boolean {
  return _accessToken !== null || DEV_TOKEN !== '';
}

/**
 * Authenticated fetch wrapper — drop-in replacement for `fetch()` that
 * auto-injects the Authorization header and credentials on every request.
 *
 * Use this instead of raw `fetch()` for any call to the admin backend.
 * Auth-exempt endpoints (login, refresh, setup) are fine too — the backend
 * simply ignores the header on exempt paths.
 */
export function authFetch(
  input: RequestInfo | URL,
  init?: RequestInit,
): Promise<Response> {
  const token = getAccessToken();
  const headers: Record<string, string> = {
    ...(init?.headers as Record<string, string>),
  };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  return fetch(input, {
    ...init,
    headers,
    credentials: 'include',
  });
}

/**
 * Authenticated SSE subscription — replacement for `new EventSource(url)`.
 *
 * Uses `authFetch` + `ReadableStream` so the JWT is sent as a header.
 * Calls `onEvent(eventName, data)` for each SSE event received.
 * Returns an AbortController so the caller can cancel the stream.
 *
 * Set `opts.reconnect` to true for long-lived streams (toast listener, TV
 * feed, monitor). When enabled, the stream auto-reconnects with exponential
 * backoff (1s → 2s → 4s … capped at 30s) on network errors or stream end,
 * matching the behaviour of the native EventSource API.
 */
export function authSSE(
  url: string,
  onEvent: (event: string, data: Record<string, unknown>) => void,
  opts?: { onError?: () => void; reconnect?: boolean },
): AbortController {
  const controller = new AbortController();
  let backoff = 1000;
  const MAX_BACKOFF = 30_000;

  function connect() {
    if (controller.signal.aborted) return;

    authFetch(url, { signal: controller.signal })
      .then(async (resp) => {
        if (!resp.ok || !resp.body) {
          opts?.onError?.();
          scheduleReconnect();
          return;
        }

        // Reset backoff on successful connection
        backoff = 1000;

        const reader = resp.body.getReader();
        const decoder = new TextDecoder();
        let buffer = '';
        let currentEvent = 'message';

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });

          const lines = buffer.split('\n');
          buffer = lines.pop() ?? '';

          for (const rawLine of lines) {
            const line = rawLine.replace(/\r$/, '');
            if (line === '') {
              currentEvent = 'message';
            } else if (line.startsWith('event: ')) {
              currentEvent = line.slice(7).trim();
            } else if (line.startsWith('data: ') || line.startsWith('data:')) {
              const dataStr = line.startsWith('data: ') ? line.slice(6) : line.slice(5);
              try {
                onEvent(currentEvent, JSON.parse(dataStr));
              } catch {
                onEvent(currentEvent, {});
              }
            }
          }
        }

        // Stream ended normally — reconnect if long-lived
        scheduleReconnect();
      })
      .catch((e) => {
        if ((e as Error).name === 'AbortError') return;
        opts?.onError?.();
        scheduleReconnect();
      });
  }

  function scheduleReconnect() {
    if (!opts?.reconnect || controller.signal.aborted) return;
    const delay = backoff;
    backoff = Math.min(backoff * 2, MAX_BACKOFF);
    setTimeout(connect, delay);
  }

  connect();
  return controller;
}
