# Copyright 2026 Ali Arda Diri, Berlin, Germany
#
# This file is part of Sagewai, licensed under the GNU Affero General
# Public License v3.0 or later (AGPL-3.0-or-later). You may use,
# modify, and distribute this file under the terms of the AGPL.
# See the LICENSE file or https://www.gnu.org/licenses/agpl-3.0.html
#
# This file is also available under a commercial license.
# See COMMERCIAL-LICENSE.md for details.
"""Public API for the generic Work domain."""

from sagewai.work.activity import (
    ACTIVITY_LOG_MAX_BYTES,
    ACTIVITY_ROW_CAP,
    FLEET_ACTIVITY_LOG_MAX_BYTES,
    ActivityKind,
    ActivityPage,
    ActivitySink,
    ActivitySource,
    ListActivitySink,
    OperatorActivity,
    WorkActivityStore,
    activity_pipeline,
    activity_redactor,
    archive_activity_log,
    bounded_ndjson,
)
from sagewai.work.activity_ingestion import ActivityIngestion, BatchingActivitySink
from sagewai.work.capsule import TaskCapsuleCompiler
from sagewai.work.completion import (
    evaluate_completion,
    fold_verification_results,
    validate_criterion_subset,
    validate_verification_result,
)
from sagewai.work.contract import AcceptanceCriterion, WorkContract
from sagewai.work.control import (
    ControlCheck,
    ControlCheckContext,
    ControlCheckResult,
    ControlDegradedError,
    OperatorController,
)
from sagewai.work.events import (
    WorkEvent,
    WorkEventType,
    active_control_precondition_ids,
    execution_attempt_from_events,
    next_stage_run,
    stage_run_ids,
    stage_runtime_failures,
)
from sagewai.work.fleet import (
    FleetOperatorResultEnvelope,
    FleetOperatorRuntime,
    FleetOperatorTaskPayload,
    FleetWorkspaceTransfer,
    FleetWorkspaceTransferResult,
    FleetWorkspaceTransport,
    NoCompatibleWorkerError,
)
from sagewai.work.harness_mcp import mcp_connection_resolver
from sagewai.work.harness_tools import FILE_SIZE_CAP, HarnessTools, as_data, build_harness_tools
from sagewai.work.metrics import WorkMetrics
from sagewai.work.models import (
    SUPERSEDED,
    Action,
    ActionIntent,
    ActionPlan,
    ActionRequest,
    ActionResult,
    ActionScope,
    Assumption,
    ClaimClassification,
    ClassifiedClaim,
    CompletionEvaluation,
    ControlPrecondition,
    ControlPreconditionKind,
    CriterionVerification,
    ExecutionAttempt,
    GateDecision,
    OperatorDisciplineReport,
    PendingAttention,
    PendingAttentionKind,
    ProposedAcceptanceCriterion,
    Reversibility,
    ReviewFinding,
    ReviewResult,
    TaskCapsule,
    VerificationResult,
    WorkAnalysisResult,
    WorkContractProposal,
    WorkDesignResult,
    WorkItem,
    WorkRecord,
)
from sagewai.work.profile import WorkProfile
from sagewai.work.runtime import (
    CapabilityGrant,
    CapabilitySet,
    ClaudeRuntime,
    CodexRuntime,
    OperatorResult,
    OperatorRuntime,
    WorkRequest,
    Workspace,
    build_operator_prompt,
)
from sagewai.work.runtime_harness import HarnessBudget, HarnessRuntime, HarnessTierResolution
from sagewai.work.store import WorkStore
from sagewai.work.supersede import supersede_work

__all__ = [
    "ACTIVITY_LOG_MAX_BYTES",
    "ACTIVITY_ROW_CAP",
    "FLEET_ACTIVITY_LOG_MAX_BYTES",
    "FILE_SIZE_CAP",
    "Action",
    "AcceptanceCriterion",
    "ActionPlan",
    "ActionRequest",
    "ActionIntent",
    "ActionResult",
    "ActionScope",
    "ActivityKind",
    "ActivityPage",
    "ActivityIngestion",
    "ActivitySink",
    "ActivitySource",
    "BatchingActivitySink",
    "CapabilityGrant",
    "Assumption",
    "CapabilitySet",
    "ClaimClassification",
    "ClassifiedClaim",
    "ClaudeRuntime",
    "CodexRuntime",
    "ControlPrecondition",
    "ControlPreconditionKind",
    "ControlCheck",
    "ControlCheckContext",
    "ControlCheckResult",
    "ControlDegradedError",
    "CompletionEvaluation",
    "CriterionVerification",
    "FleetOperatorRuntime",
    "FleetOperatorResultEnvelope",
    "FleetOperatorTaskPayload",
    "FleetWorkspaceTransferResult",
    "FleetWorkspaceTransfer",
    "FleetWorkspaceTransport",
    "HarnessTools",
    "HarnessBudget",
    "HarnessRuntime",
    "HarnessTierResolution",
    "NoCompatibleWorkerError",
    "ExecutionAttempt",
    "GateDecision",
    "ListActivitySink",
    "OperatorActivity",
    "PendingAttention",
    "PendingAttentionKind",
    "ProposedAcceptanceCriterion",
    "OperatorDisciplineReport",
    "OperatorResult",
    "OperatorRuntime",
    "OperatorController",
    "Reversibility",
    "TaskCapsule",
    "ReviewFinding",
    "ReviewResult",
    "SUPERSEDED",
    "TaskCapsuleCompiler",
    "WorkContract",
    "WorkEvent",
    "WorkMetrics",
    "VerificationResult",
    "WorkAnalysisResult",
    "WorkActivityStore",
    "WorkContractProposal",
    "WorkDesignResult",
    "WorkEventType",
    "WorkItem",
    "WorkRecord",
    "WorkRequest",
    "WorkProfile",
    "WorkStore",
    "Workspace",
    "active_control_precondition_ids",
    "activity_pipeline",
    "activity_redactor",
    "as_data",
    "archive_activity_log",
    "build_harness_tools",
    "build_operator_prompt",
    "bounded_ndjson",
    "execution_attempt_from_events",
    "evaluate_completion",
    "fold_verification_results",
    "mcp_connection_resolver",
    "next_stage_run",
    "stage_run_ids",
    "stage_runtime_failures",
    "supersede_work",
    "validate_criterion_subset",
    "validate_verification_result",
]
