# Copyright 2026 Ali Arda Diri, Berlin, Germany
#
# This file is part of Sagewai, licensed under the GNU Affero General
# Public License v3.0 or later (AGPL-3.0-or-later). You may use,
# modify, and distribute this file under the terms of the AGPL.
# See the LICENSE file or https://www.gnu.org/licenses/agpl-3.0.html
#
# This file is also available under a commercial license.
# See COMMERCIAL-LICENSE.md for details.
"""Slot specifications for autopilot blueprints.

A :class:`SlotSpec` describes a single parameter that a blueprint needs
to be bound to at mission-creation time. It carries a type hint
(as a string, since pydantic handles the real typing on the blueprint
itself), an optional default, and an optional named validator.

Validation is dispatched through the :class:`ValidatorRegistry` so that
blueprints stored as YAML (or generated by the hosted Sagewai LLM
service) never need to ship Python callables.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from .errors import SlotValidationError
from .validators import ValidatorRegistry


class SlotSpec(BaseModel):
    """Declarative spec for one slot on a :class:`Blueprint`."""

    model_config = ConfigDict(frozen=True)

    type_: str  # documentation-only hint, e.g. "list[str]"
    description: str
    required: bool = True
    default: Any = None
    validator_name: str | None = None

    def validate_value(
        self,
        value: Any,
        *,
        slot_name: str,
        registry: ValidatorRegistry,
    ) -> Any:
        """Validate ``value`` for this slot, returning the normalized value.

        Semantics:

        - ``None`` and the slot is required  → :class:`SlotValidationError`.
        - ``None`` and the slot is optional  → return ``self.default``.
        - Otherwise, dispatch to the named validator if one is set;
          otherwise return the value untouched.
        """
        if value is None:
            if self.required:
                raise SlotValidationError(slot_name, "required slot missing")
            return self.default

        if self.validator_name is None:
            return value

        try:
            validator = registry.get(self.validator_name)
        except KeyError as exc:
            raise SlotValidationError(
                slot_name,
                f"unknown validator {self.validator_name!r}",
            ) from exc
        return validator(value, slot_name=slot_name)
